"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
var hono_1 = require("hono");
var node_server_1 = require("@hono/node-server");
var seleniumWebForm_js_1 = require("./handlers/seleniumWebForm.js");
var app = new hono_1.Hono();
var selenium = new hono_1.Hono();
selenium.post("/webform", seleniumWebForm_js_1.seleniumWebFormHandler);
app.route("/selenium", selenium);
app.get("/healthz", function (c) { return c.text("ok"); });
var port = Number((_a = process.env.PORT) !== null && _a !== void 0 ? _a : 8080);
(0, node_server_1.serve)({ fetch: app.fetch, port: port });
